### ISSUE TITLE
Incompatible with Hold Scan Button mod as of v1.0.1/2

### ISSUE THREAD

**Issue by Nelots** [ProfX66/ShipLootPlus#1]
When I scan items in my ship with only this mod and [Hold Scan Button](https://thunderstore.io/c/lethal-company/p/FutureSavior/Hold_Scan_Button/) (+BepInEx & Lethal Config) active, I will occasionally get a CTD. This does not happen with v1.0.0.

**Comment by ProfX66** [comment]
When you get a chance, please try the latest version (1.0.3), it should have a fix for this.

**Comment by Nelots** [comment]
With the updated version, I'm no longer able to trigger a CTD, so it seems to be fixed now.

**Comment by ProfX66** [comment]
Awesome! Glad to hear, I'm going to go ahead and close this issue, please re-open if you see this again.
