### ISSUE TITLE
scan spam will crash game

### ISSUE THREAD

**Issue by riverbible** [ProfX66/ShipLootPlus#2]
Hello! ShipLootPlus Developer!

I discovered a critical error today that may prevent you from playing the game.

I discovered an error that caused the game to crash if the player spam the scan button.

I confirmed that this error occurs starting from version 1.0.1 or higher. (Continues to occur even in the latest version)

I hope there is a quick fix, and thank you for always developing mods.

Here is the error log.
![20240130_015002](https://github.com/ProfX66/ShipLootPlus/assets/155571938/78cb9883-e8b6-4eb2-b479-522b82e46a98)

**Comment by riverbible** [comment]
Well OK! Here is my Testing profile code
018d563b-ec8f-c730-efb3-a909bc51b653

**Comment by ProfX66** [comment]
When you get a chance, please try the latest version (1.0.3), it should have a fix for this.
