### ISSUE TITLE
Interact (E) spam is crash game

### ISSUE THREAD

**Issue by riverbible** [ProfX66/ShipLootPlus#4]
Hello! ShipLootPlus Developer!

I discovered another critical error today that may prevent you from playing the game.

Perhaps this appears to be a similar type of error as last time scan spam.

Now, I spam Interact (E button), the game will crash.

I hope there is a quick fix, and thank you for always developing mods.

Here is the error log.
![20240130_120630](https://github.com/ProfX66/ShipLootPlus/assets/155571938/a8a73d74-d017-4cb3-8884-4023f692d701)

**Comment by ProfX66** [comment]
I just published a new version (1.0.4) which should fix this issue. It also has some more optimization which should stop any event being spammed from causing lag or crashes.
