### ISSUE TITLE
Unable To Load Mod While Having  BepinEx MLLoader

### ISSUE THREAD

**Issue by AmyRose1288** [ProfX66/ShipLootPlus#5]
[Info   :ShipLootPlus] Initializing plugin: ShipLootPlus v1.0.5 by PXC
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MelonLoader.MonoInternals.ResolveInternals.AssemblyManager+<>c.<Setup>b__1_0 (System.Object sender, System.ResolveEventArgs args) (at <25dbf314fe56482eac5c1b90ce520669>:IL_0025)
System.AppDomain.DoAssemblyResolve (System.String name, System.Reflection.Assembly requestingAssembly, System.Boolean refonly) (at <787acc3c9a4c471ba7d971300105af24>:IL_0075)
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly, System.Threading.StackCrawlMark& stackMark) (at <787acc3c9a4c471ba7d971300105af24>:IL_0021)
System.AppDomain.Load (System.String assemblyString) (at <787acc3c9a4c471ba7d971300105af24>:IL_0002)
(wrapper remoting-invoke-with-check) System.AppDomain.Load(string)
ShipLootPlus.ShipLootPlus.AssemblyExists (System.String Name) (at <644b8feddb9247f5a80c0a4861456641>:IL_0005)
ShipLootPlus.ShipLootPlus.Awake () (at <644b8feddb9247f5a80c0a4861456641>:IL_0041)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

Modpack Code:018d65ee-6a60-9161-ba4e-7eb3561f1543

**Comment by ProfX66** [comment]
I have seen melon loader have all kinds of issues with many mods (as its an alternative to BepInEx), I'm not entirely sure why its failing on a part where i'm just looking to see if LethalConfig exists or not. Like there is nothing im doing there that is weird, but I will look into it and see if its something I can fix.

**Comment by ProfX66** [comment]
Please try the newly published version 1.0.6 and let me know if it works for you.

**Comment by AmyRose1288** [comment]
it worked!!thanks for update

**Comment by ProfX66** [comment]
Awesome and np!
