### ISSUE TITLE
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CoolLKKPS** [ProfX66/ShipLootPlus#9]
[08:54:11.9393752] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ShipLootPlus.Utils.UiHelper+<>c__DisplayClass63_0.<CalculateLootValue>b__3 (GrabbableObject s) (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
System.Linq.Enumerable+WhereArrayIterator\`1[TSource].ToList () (at <dab7f68612224ba3ae40f651d44f9d4c>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable\`1[T] source) (at <dab7f68612224ba3ae40f651d44f9d4c>:0)
ShipLootPlus.Utils.UiHelper.CalculateLootValue (System.Collections.Generic.List\`1[T] Ignored, System.String scope) (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
ShipLootPlus.Utils.UiHelper.RefreshElementValues () (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
ShipLootPlus.Patches.StartOfRoundPatcher.SetMapScreenInfoToCurrentLevel () (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::SetMapScreenInfoToCurrentLevel>(StartOfRound)
StartOfRound.ChangePlanet () (at <126a87ecbe81427089f4bae3b253432b>:0)
StartOfRound.ArriveAtLevel () (at <126a87ecbe81427089f4bae3b253432b>:0)
StartOfRound+<TravelToLevelEffects>d__299.MoveNext () (at <126a87ecbe81427089f4bae3b253432b>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

[08:54:11.9404267] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ShipLootPlus.Utils.UiHelper+<>c__DisplayClass63_0.<CalculateLootValue>b__3 (GrabbableObject s) (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
System.Linq.Enumerable+WhereArrayIterator\`1[TSource].ToList () (at <dab7f68612224ba3ae40f651d44f9d4c>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable\`1[T] source) (at <dab7f68612224ba3ae40f651d44f9d4c>:0)
ShipLootPlus.Utils.UiHelper.CalculateLootValue (System.Collections.Generic.List\`1[T] Ignored, System.String scope) (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
ShipLootPlus.Utils.UiHelper.RefreshElementValues () (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
ShipLootPlus.Patches.StartOfRoundPatcher.SetMapScreenInfoToCurrentLevel () (at <3f494e19ae784aeaadfbdc6da6528c1f>:0)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::SetMapScreenInfoToCurrentLevel>(StartOfRound)
StartOfRound.ChangePlanet () (at <126a87ecbe81427089f4bae3b253432b>:0)
StartOfRound.ArriveAtLevel () (at <126a87ecbe81427089f4bae3b253432b>:0)
StartOfRound+<TravelToLevelEffects>d__299.MoveNext () (at <126a87ecbe81427089f4bae3b253432b>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

[08:53:39.7217289] [Error  : Unity Log] [Netcode] NetworkPrefab hash was not found! In-Scene placed NetworkObject soft synchronization failure for Hash: 0!

**Comment by CoolLKKPS** [comment]
@ProfX66

**Comment by CoolLKKPS** [comment]
on game version v50

**Comment by ProfX66** [comment]
This is already fixed in my unreleased version, which should be releasing this weekend.

**Comment by CoolLKKPS** [comment]
nice!

**Comment by ProfX66** [comment]
This took me longer to get out than I expected due to some unexpected IRL things, but it's just been published to Thunderstore! (fixed in commit 2499be1)
